defmodule DoneManager.Tasks do
  @moduledoc """
  Tasks and their occurrences.

  Read/write functions take a `%Scope{}` and only ever touch the scope's
  household, so cross-household access is structurally impossible. Completion
  status is stored on the occurrence (`completed_at`, `completed_by_id`). In the
  current slice a task is created with one eager occurrence; the single-invariant
  reconcile loop comes later. See architecture/stages.md and
  architecture/scheduling.md.
  """

  import Ecto.Query, warn: false
  require Logger

  alias DoneManager.Accounts.Scope
  alias DoneManager.Accounts.User
  alias DoneManager.Households.Household
  alias DoneManager.Households.HouseholdMembership
  alias DoneManager.Repo
  alias DoneManager.Tasks.Task
  alias DoneManager.Tasks.TaskOccurrence
  alias DoneManager.Tasks.TaskStatus

  ## Tasks

  @doc "Tasks in the scope's current household, newest first."
  def list_tasks(%Scope{household: %Household{id: household_id}}) do
    from(t in Task, where: t.household_id == ^household_id, order_by: [desc: t.inserted_at])
    |> Repo.all()
  end

  @doc """
  Fetches a task by its (globally unique) id, but only if the scope's user is a
  member of the task's household, or raises (default-deny). Keyed on membership
  rather than the current household so a by-id route resolves the right
  household regardless of which one is currently selected.
  """
  def get_task!(%Scope{user: %User{id: user_id}}, id) do
    from(t in Task,
      join: m in HouseholdMembership,
      on: m.household_id == t.household_id,
      where: t.id == ^id and m.user_id == ^user_id
    )
    |> Repo.one!()
  end

  @doc """
  Creates a task in the scope's current household and eagerly generates its
  current occurrence, with `due_at`/`expires_at` computed in the household
  timezone (see architecture/scheduling.md), so an execute has something to act
  on before the reconcile loop exists.
  """
  def create_task(%Scope{household: %Household{} = household}, attrs) do
    Repo.transaction(fn ->
      task =
        %Task{household_id: household.id}
        |> Task.changeset(attrs)
        |> Repo.insert()
        |> unwrap()

      task |> insert_occurrence(household.timezone) |> unwrap()
      task
    end)
  end

  @doc """
  Updates a task and ensures it still has one open occurrence (create/update
  upserts the open occurrence; see architecture/scheduling.md). The task must
  already have been loaded through a scope.
  """
  def update_task(%Scope{household: %Household{id: household_id}}, %Task{} = task, attrs) do
    if task.household_id == household_id do
      with {:ok, task} <- task |> Task.changeset(attrs) |> Repo.update() do
        current_or_create_occurrence(task)
        {:ok, task}
      end
    else
      {:error, :unauthorized}
    end
  end

  def change_task(%Task{} = task \\ %Task{}, attrs \\ %{}), do: Task.changeset(task, attrs)

  @doc """
  Ensures every active scheduled/interval task has one open occurrence.

  The reconcile loop is idempotent: unresolved occurrences are left alone, and
  inserts are backed by the `(task_id, due_at)` unique index for race safety.
  Timer tasks are intentionally excluded; they are generated by user action.

  After generating, each task is audited against the single invariant ("exactly
  one open occurrence") and any violation is logged. Generation gaps otherwise
  surface only when a member taps a tag at the wrong minute — often once a day on
  a single task — so the loop checks its own postcondition every tick.
  """
  def reconcile_occurrences(now \\ DateTime.utc_now()) do
    from(t in Task,
      where: t.active and t.task_type in ["scheduled", "interval"],
      preload: [:household]
    )
    |> Repo.all()
    |> Enum.each(fn task ->
      reconcile_task_occurrence(task, now)
      audit_open_occurrence(task, now)
    end)

    :ok
  end

  # The invariant is "exactly one open occurrence per active task." After a
  # reconcile tick it should hold, so a breach means generation stalled or
  # double-inserted. The one benign exception is completing a scheduled slot
  # *before* its due_time: the next slot collides with the current one and is
  # skipped until due_time passes (see architecture/scheduling.md), leaving zero
  # open occurrences with a completed, not-yet-due latest — not logged.
  defp audit_open_occurrence(%Task{} = task, now) do
    open_count = open_occurrence_count(task, now)
    latest = current_occurrence(task)

    cond do
      is_nil(latest) ->
        log_invariant(task, "has no occurrences at all")

      open_count > 1 ->
        log_invariant(task, "has #{open_count} open occurrences (expected 1)")

      open_count == 0 and not completed_before_due?(latest, now) ->
        log_invariant(task, "has no open occurrence; generation may be stalled")

      true ->
        :ok
    end
  end

  defp open_occurrence_count(%Task{id: task_id}, now) do
    from(o in TaskOccurrence,
      where:
        o.task_id == ^task_id and is_nil(o.completed_at) and
          (is_nil(o.expires_at) or o.expires_at > ^now)
    )
    |> Repo.aggregate(:count)
  end

  defp completed_before_due?(%TaskOccurrence{completed_at: %DateTime{}, due_at: due_at}, now),
    do: DateTime.compare(due_at, now) == :gt

  defp completed_before_due?(_occurrence, _now), do: false

  defp log_invariant(%Task{id: id, name: name}, detail) do
    Logger.error("reconcile invariant breach: task #{id} (#{inspect(name)}) #{detail}")
  end

  ## Occurrences

  @doc "The current (most recent) occurrence for a task, or nil."
  def current_occurrence(%Task{id: task_id}) do
    from(o in TaskOccurrence,
      where: o.task_id == ^task_id,
      order_by: [desc: o.inserted_at],
      limit: 1,
      preload: [:completed_by]
    )
    |> Repo.one()
  end

  @doc "The most recent completed occurrence for a task, or nil."
  def last_completed_occurrence(%Task{id: task_id}) do
    from(o in TaskOccurrence,
      where: o.task_id == ^task_id and not is_nil(o.completed_at),
      order_by: [desc: o.completed_at],
      limit: 1,
      preload: [:completed_by]
    )
    |> Repo.one()
  end

  @doc """
  The task's clock-aware display status (see `DoneManager.Tasks.TaskStatus`).

  Loads the household timezone and the occurrences the derivation needs. Pass a
  fixed `now` to make the result deterministic in tests.
  """
  def task_status(%Task{} = task, now \\ DateTime.utc_now()) do
    task = Repo.preload(task, :household)

    TaskStatus.derive(
      task,
      current_occurrence(task),
      last_completed_occurrence(task),
      task.household.timezone,
      now
    )
  end

  @doc """
  The task's current occurrence, generating one if none exists. The eager
  occurrence makes this rare, but an execute must always have something to act
  on, so the path self-heals rather than failing.
  """
  def current_or_create_occurrence(%Task{} = task) do
    case current_occurrence(task) do
      nil ->
        task |> insert_occurrence(task_timezone(task)) |> unwrap_occurrence()

      %TaskOccurrence{} = occurrence when task.task_type == "timer" ->
        if TaskOccurrence.done?(occurrence) do
          task |> insert_occurrence(task_timezone(task)) |> unwrap_occurrence()
        else
          occurrence
        end

      occurrence ->
        occurrence
    end
  end

  @doc """
  Fetches an occurrence by id, but only if the scope's user is a member of its
  task's household, or raises (default-deny). Task and `completed_by` preloaded.
  """
  def get_occurrence!(%Scope{user: %User{id: user_id}}, id) do
    from(o in TaskOccurrence,
      join: t in Task,
      on: t.id == o.task_id,
      join: m in HouseholdMembership,
      on: m.household_id == t.household_id,
      where: o.id == ^id and m.user_id == ^user_id,
      preload: [:completed_by, task: :household]
    )
    |> Repo.one!()
  end

  @doc "Whether an occurrence has been completed."
  def done?(%TaskOccurrence{} = occurrence), do: TaskOccurrence.done?(occurrence)

  @doc """
  Completes an occurrence, attributed to `user_id`. Idempotent: if it was
  already done it is not re-stamped. Returns `{:completed, occurrence}` or
  `{:duplicate, occurrence}`.
  """
  def complete_occurrence(%TaskOccurrence{} = occurrence, user_id) do
    if TaskOccurrence.done?(occurrence) do
      {:duplicate, occurrence}
    else
      occurrence =
        occurrence
        |> TaskOccurrence.changeset(%{
          completed_at: DateTime.utc_now(),
          completed_by_id: user_id
        })
        |> Repo.update()
        |> unwrap()
        |> Repo.preload([:completed_by, task: :household])

      {:completed, occurrence}
    end
  end

  @doc """
  Starts a timer occurrence by setting its due time to now plus the task interval.

  Reloading an already-running timer is idempotent: it returns `:running` and
  does not extend the due time.
  """
  def start_timer_occurrence(%TaskOccurrence{task: %Task{task_type: "timer"} = task} = occurrence) do
    now = DateTime.utc_now()

    cond do
      TaskOccurrence.done?(occurrence) ->
        {:completed, occurrence}

      DateTime.compare(occurrence.due_at, now) == :gt ->
        {:running, occurrence}

      true ->
        occurrence =
          occurrence
          |> TaskOccurrence.changeset(%{
            due_at: DateTime.add(now, task.interval_minutes, :minute)
          })
          |> Repo.update()
          |> unwrap()
          |> Repo.preload([:completed_by, task: :household])

        {:started, occurrence}
    end
  end

  @doc """
  Cancels a running timer occurrence by deleting it.
  """
  def cancel_timer_occurrence(%TaskOccurrence{task: %Task{task_type: "timer"}} = occurrence) do
    Repo.delete(occurrence)
  end

  @doc """
  Completes a task's current occurrence from the web UI, attributed to the
  scope's user — the same mechanism as a tap. The task must already have been
  loaded through a scope (membership-checked). Returns `{:ok, :completed}` or
  `{:ok, :duplicate}`.
  """
  def complete_via_web(
        %Scope{user: %User{id: user_id}, household: %Household{id: household_id}},
        %Task{household_id: household_id} = task
      ) do
    {outcome, _occurrence} =
      task |> current_or_create_occurrence() |> complete_occurrence(user_id)

    {:ok, outcome}
  end

  def complete_via_web(_scope, _task), do: {:error, :unauthorized}

  defp insert_occurrence(%Task{} = task, timezone) do
    task
    |> Ecto.build_assoc(:occurrences)
    |> TaskOccurrence.changeset(TaskOccurrence.schedule_attrs(task, timezone))
    |> Repo.insert()
  end

  defp reconcile_task_occurrence(%Task{} = task, now) do
    case current_occurrence(task) do
      nil ->
        task
        |> Ecto.build_assoc(:occurrences)
        |> TaskOccurrence.changeset(TaskOccurrence.schedule_attrs(task, task_timezone(task), now))
        |> insert_reconciled_occurrence()

      %TaskOccurrence{} = occurrence ->
        if TaskOccurrence.resolved?(occurrence, now) do
          task
          |> Ecto.build_assoc(:occurrences)
          |> TaskOccurrence.changeset(
            TaskOccurrence.next_schedule_attrs(task, task_timezone(task), occurrence, now)
          )
          |> insert_reconciled_occurrence()
        end
    end
  end

  defp insert_reconciled_occurrence(changeset) do
    Repo.insert(changeset,
      on_conflict: :nothing,
      conflict_target: [:task_id, :due_at]
    )
  end

  defp task_timezone(%Task{household: %Household{timezone: timezone}}), do: timezone
  defp task_timezone(%Task{} = task), do: Repo.preload(task, :household).household.timezone

  defp unwrap_occurrence({:ok, occurrence}), do: Repo.preload(occurrence, :completed_by)

  defp unwrap({:ok, record}), do: record
  defp unwrap({:error, changeset}), do: Repo.rollback(changeset)
end
